### ISSUE TITLE
Sometimes shooting the correct answer does not destroy all incorrect answer ships

### ISSUE THREAD

**Issue by xow** [xow/moodle-mod_quizgame#13]
This fills the screen with too many ships causing confusion

**Comment by KaijCHEN** [comment]
seems like developer left this problem for 4yrs...

**Comment by xow** [comment]
Yep that's right. Wow I can't believe it's been that long. No longer actively in the moodle community. Still very much open to contributions though

**Comment by sbourget** [comment]
This should now be fixed as part of #58 and will be available in the next release.
