### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by dougti** [xow/moodle-mod_quizgame#16]
The user should be presented with the option of fullscreen, but it shouldn't be activated by default.

When the user leaves fullscreen, the canvas size isn't redrawn to fit within its containers.

Other than that, good work!

**Comment by xow** [comment]
Thanks for the bug report. I appreciate it a lot! Hopefully I will get time to fix this soon.

If you have coding experience feel free to submit a patch :D

**Comment by dougti** [comment]
I'm afraid I'm not much of a programmer, but ripping out the "fullscreen" calls did what I needed.
The window now expands to fit within its CSS containers, without bugging out like it does when you exit fullscreen. I'm then just using CSS to dynamically resize the window/container.

- 44: function sizeScreen(stage, width, height, fullscreen) {
+ 44: function sizeScreen(stage, width, height) {
- 53-56
- 101-110

I've also tweaked the font sizing & placing a bit for legibility. I'm using it for language students, so the text needs to be nice & clear.

Menu: 30px
Score: 25px (pos. 10, 30)
Question: 30px (pos. displayRect.width/2, 35)
EoG: 30px
Enemies: 19px

**Comment by xow** [comment]
This game can be useful for language learning so I think that having bigger font sizes would be a great idea. Added #18

**Comment by deraadt** [comment]
The game now has a full-screen capability, but there is no choice of whether to use this or no.

Also, when you return from full-screen, the game stays on the regular page.

**Comment by xow** [comment]
Fixed in d29eb3c
