### ISSUE TITLE
Deprecation message shown

### ISSUE THREAD

**Issue by deraadt** [xow/moodle-mod_quizgame#19]
The following message is shown.

    Function moodleform_mod::add_intro_editor() is deprecated, use moodleform_mod::standard_intro_elements() instead.

        line 710 of /course/moodleform_mod.php: call to debugging()
        line 62 of /mod/quizgame/mod_form.php: call to moodleform_mod->add_intro_editor()
        line 196 of /lib/formslib.php: call to mod_quizgame_mod_form->definition()
        line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
        line 255 of /course/modedit.php: call to moodleform_mod->moodleform_mod()

I also noticed some things you might want to clean up at the same time.
* There are some style issues reported by the code checker
* Some tags are included as raw HTML
* The docs are not linked fromm the config page (you might want to put a redirect in the docs)

**Comment by xow** [comment]
Thanks, forgot to update that before pushing the 3.0 version

Will look at this and the other problems soon

**Comment by xow** [comment]
Fixed the docs with the rediract and deprecation message in 7f6905c. Split other issues into #20 and #21.

Thanks for reporting this issue. Closed

**Comment by xow** [comment]
Noting here that the coding style errors have now been fixed in 55e1478 and 414cc96 as part of #21

**Comment by deraadt** [comment]
Right on, brutha.
