### ISSUE TITLE
Add support for moodle 3.4 and 3.5

### ISSUE THREAD

**Issue by xow** [xow/moodle-mod_quizgame#41]

**Comment by richpav** [comment]
I'm new at Moodle and I'm working on setting up a mobile site ASAP for young EFL learners in Japan. Any idea how long before a 3.4 compatible version will be available? Or should I switch to Moodle 3.3?

**Comment by xow** [comment]
Released 3.5-r1

**Comment by xow** [comment]
@richpav This is available for 3.4 (and 3.5 too) now!
