### ISSUE TITLE
Long question text extends beyond the edges

### ISSUE THREAD

**Issue by kalenhussey** [xow/moodle-mod_quizgame#46]
Our questions are longish science definitions and the text stays on one line and extends past the edges of the screen so you can't read the full question. Also, shorter questions that fit on a regular desktop or laptop screen still can't be read on a mobile device for the same reason. I can't get breaks ( < br > or < br / > ) to work, but I imagine even if I could, the questions would still extend beyond the edge on mobile devices.

Attached are two mobile examples:

![quizventure mobile example 1](https://user-images.githubusercontent.com/42651222/44540446-102d3880-a6c4-11e8-914b-ddc08e747b31.jpg)

![quizventure mobile example 2](https://user-images.githubusercontent.com/42651222/44540447-102d3880-a6c4-11e8-92d7-31e3d58bbccd.jpg)

**Comment by sbourget** [comment]
This was recently fixed by PR #49 which added better support for mobile devices..  The fix will be available in the next release.  Thank you for the report.
