### ISSUE TITLE
Sticking after question

### ISSUE THREAD

**Issue by Shad-334** [xow/moodle-mod_quizgame#47]
Hi, I fantastic plugin, but I have an issue:

I'm using multiple choice - multiple answer questions and once all answers are shot down from the first question the quiz does not move on to the next question, what am I doing wrong?

I have to refresh to get it to move to the next question.

Kev

**Comment by xow** [comment]
How many questions are in your question bank? Are there any duplicates?

What browser is this?

**Comment by Shad-334** [comment]
There are 10 questions in the bank, all multiple choice, multiple answers. no duplicates.
Ive tested it with Google Chrome and Firefox with the same results.

**Comment by sbourget** [comment]
This should now be fixed as part of #58 and will be available as part of the next release.
