### ISSUE TITLE
Unit test failure: need to implement core_userlist_provider for moodles >= 3.6

### ISSUE THREAD

**Issue by kristian-94** [xow/moodle-mod_quizgame#72]
We get this failure:

>  provider_testcase::test_userdata_provider_implements_userlist with data set "mod_quizgame" ('mod_quizgame', 'mod_quizgame\privacy\provider')
> Failed asserting that false is true.
> 
> /var/www/site/privacy/tests/provider_test.php:213
> /var/www/site/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
>  vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

Need to implement core_userlist_provider in our privacy API class. https://docs.moodle.org/dev/Privacy_API#Retrieving_the_users_in_a_context

**Comment by sbourget** [comment]
This was fixed in the 3.11 release
