### ISSUE TITLE
End game when there are no more questions.

### ISSUE THREAD

**Issue by Ingrid-E** [xow/moodle-mod_quizgame#74]
I was doing some examples with Quizventure and if I only had 3 questions, the game would go on a loop if my leaves are >0 but if the person got right the 3 questions and still had lives the game never ends. I think there should be an option for it to end, even if you still have lives.

**Comment by xow** [comment]
For context, the current behaviour is that once you cycle through all the questions, it does it again, but with faster enemies, to make it harder. That should either be clearer in the UI or yeah have a way for it to end instead
