### ISSUE TITLE
Fix the i_add_to_section_and_i_fill_the_form_with deprecation for Moodle 4.4

### ISSUE THREAD

**Issue by Julian-Tovar** [xow/moodle-mod_quizgame#85]
Good day team,

In Moodle 4.4 this Behat step was deprecated:

``` behat
When I add a "Quizventure" to section "1" and I fill the form with:
```

This step can be found in file 'tests/behat/quizgame_add.feature'.

I attach this patch, as a way to fix this issue from Behat tests for Moodle 4.4. 
[mod_quizgame_behat_fix_4.4.patch](https://github.com/user-attachments/files/17263182/mod_quizgame_behat_fix_4.4.patch)

Let me know if this patch is acceptable or if it contains mistakes or missing parts, and if I should create a PR with it or if you apply it on your side in that case. 

Thank you.

**Comment by sbourget** [comment]
This should have just been fixed by #84
